import os
from building import *

src = []
objs = []
cwd  = GetCurrentDir()

CPPPATH = [cwd]
CPPPATH += [cwd + '/port']
CPPPATH += [cwd + '/renesas-ra']
CPPPATH += [cwd + '/port/rtthread_port']

src = Glob('port/*.c')
src += Glob('renesas-ra/*.c')
src += Glob('port/rtthread_port/*.c')

objs = DefineGroup('micropython/port', src, depend = [''], CPPPATH = CPPPATH)

Return('objs')
