import os
from building import *

group = []
src = []
objs = []
cwd  = GetCurrentDir()

CPPPATH = [cwd]
CPPPATH += [cwd + '/port']
CPPPATH += [cwd + '/port/rtthread_port']
CPPPATH += [cwd + '/port/rtthread_port/machine']

src = Glob('port/*.c')

rtt_src = Glob('port/rtthread_port/*.c')
rtt_src += Glob('port/rtthread_port/machine/*.c')

group = group + DefineGroup('micropython/rtt_port', rtt_src, depend = [''])
group = group + DefineGroup('micropython/port', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
